language: node_js
node_js:
  - 12.16.1
cache: 
  directories:
    - node_modules

install:
  - npm ci

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
