language: node_js
node_js:
  - 12.16.1
cache: 
  directories:
    - node_modules

install:
  - npm ci

script:
  - npm run build

deploy:
  if: branch = master
  edge: true
  provider: pages
  strategy: git
  token: $GITHUB_TOKEN
  target_branch: gh-pages
  local_dir: dist
  on:
    branch: master
