language: node_js
node_js:
  - 12.16.1
cache: 
  directories:
    - node_modules

git:
  depth: 3

branches:
  only:
    - master

install:
  - npm ci

script:
  - npm run build:prerender


deploy:
  edge: true
  provider: pages
  strategy: git
  token: $GITHUB_TOKEN
  target_branch: gh-pages
  local_dir: dist
  on:
    branch: master
